name: opencv_dart
description: "OpenCV4 bindings for Dart language"
version: 0.0.3-dev.1
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  w_common: ^3.0.1
  ffi: ^2.1.0
  equatable: ^2.0.5

dev_dependencies:
  ffigen: ^11.0.0
  image: ^4.1.4
  logging: ^1.2.0
  test: ^1.25.2

topics:
  - opencv
  - image

platforms:
  android:
  linux:
  windows:

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
