name: TEST build for macos arm64

on:
  push:
    branches: [ "macos_apple_silicon" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "macos_apple_silicon" ]

env:
  ANDROID_NDK_VERSION: r26c
  OPENCV_VERSION: 4.9.0

jobs:
  build-macos-arm64:
    name: build-macos-arm64
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup
        run: |
          # brew update
          brew install --force --overwrite ninja ccache ffmpeg
          cd ${{github.workspace}}
      - name: build
        run: |
          python3 scripts/build.py --opencv --src src --build-dir build macos --arch arm64
          python3 scripts/build.py --dart --src src --build-dir build macos --arch arm64
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"

      - uses: actions/upload-artifact@v4
        name: upload-libopencv_dart-macos-arm64
        with:
          path: build/publish/libopencv_dart-macos-arm64.tar.gz
          name: libopencv_dart-macos-arm64.tar.gz
      - name: Run Test
        run: |
          ls -alh $GITHUB_WORKSPACE/macos
          export DYLD_LIBRARY_PATH=$GITHUB_WORKSPACE/macos:$DYLD_LIBRARY_PATH
          flutter pub get
          flutter test -x no-local-files
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: false
          files: |
            build/publish/libopencv_dart-macos-arm64.tar.gz
