name: TESTING build for macos 

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ "main" ]

env:
  ANDROID_NDK_VERSION: r26c
  OPENCV_VERSION: 4.9.0

jobs:
  build-macos:
    name: build-macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup
        run: |
          # brew update
          brew install --force --overwrite ninja ccache ffmpeg
          cd ${{github.workspace}}
      - name: build
        run: |
          python3 scripts/build.py --opencv --os macos --arch x64 --src src --build-dir build
          python3 scripts/build.py --dart --os macos --arch x64 --src src --build-dir build
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"
      - uses: actions/upload-artifact@v4
        name: upload-libopencv_dart-macos-x64
        with:
          path: build/publish/libopencv_dart-macos-x64.tar.gz
          name: libopencv_dart-macos-x64.tar.gz
      - name: Run Test
        run: |
          ls -alh $GITHUB_WORKSPACE/macos
          export "DYLD_LIBRARY_PATH=$GITHUB_WORKSPACE/macos:$DYLD_LIBRARY_PATH"
          flutter pub get
          flutter test -x no-local-files
    #   - name: Release
    #     uses: softprops/action-gh-release@v1
    #     if: startsWith(github.ref, 'refs/tags/')
    #     with:
    #       draft: true
    #       prerelease: false
    #       files: |
    #         build/publish/libopencv_dart-macos-x64.tar.gz