name: Dart Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt install curl git wget build-essential ffmpeg libgtk-3-dev libavcodec-dev python3 neovim cmake ninja-build libswscale-dev libavformat-dev libeigen3-dev ccache nasm
          echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/linux:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          flutter pub get
          dart run opencv_dart:setup -p linux -a x64

      - name: Run tests
        run: flutter test -x skip-workflow

  test_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"

      - name: Install dependencies
        run: |
          flutter pub get
          dart run opencv_dart:setup -p windows -a x64

      - name: Run tests
        shell: pwsh
        run: |
          $env:PATH = "${{github.workspace}}\windows;${env:PATH}"
          echo "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          flutter test
