name: Dart Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: 'stable'

      - name: Set env
        run: export LD_LIBRARY_PATH=./linux:$LD_LIBRARY_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test test/

  test_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: 'stable'

      - name: Set env
        run: $ENV:PATH += ";./windows"

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test test/
