name: Examples

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  windows:
    name: windows
    runs-on: windows-2019
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: build
        run: |
          cd example
          flutter build windows
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git wget python3 unzip build-essential \
            libgtk-3-dev ffmpeg libavcodec-dev \
            cmake ninja-build nasm libavformat-dev libavutil-dev \
            libswscale-dev libgflags-dev \
            libjpeg-dev libpng-dev libtiff-dev python3-pip
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: build
        run: |
          cd example
          flutter build linux
          flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
  macos:
    name: macos
    runs-on: macos-13
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: build
        run: |
          cd example
          flutter build macos
          flutter build ios --release --no-codesign
  macos-arm:
    name: macos-arm
    runs-on: macos-14
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: build
        run: |
          cd example
          flutter build macos
          flutter build ios --release --no-codesign
